

# Install and load packages needed for analysis

install.packages("tidyverse")
install.packages("tidycensus")
install.packages("tigris") # contains spatials shape files
install.packages("sf") # manipulates geospatial data
install.packages("mapview")

library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
options(tigris_class = "sf")
library(mapview)

###############################################

# Data was pulled from the census website using the Tidycensus package. 
# To get the data, an API key was generated by filling a short signup form at: 
# https://api.census.gov/data/key_signup.html

# Get census API key
api_key <- "Your API Key"
census_api_key(api_key, install = TRUE)

### Data preparation 

# import table variable mapping that has information about census tables
table_var <- read_csv("ACS2018_Table_Shells.csv") %>% select(-`Data Release`)

# clean table_var by removing NA
table_var_clean <- na.omit(table_var) %>% 
  filter(str_detect(table_var_clean$Stub, "[:]", negate = TRUE))

# Get data about "PLACE OF BIRTH BY NATIVITY AND CITIZENSHIP STATUS" from the census
nativity_od <- get_acs(geography = "state", table = "B05002", survey = "acs5")

# Rename column "variable" to "UniqueID" in nativity df and select columns needed for analysis
nativity <- nativity_od %>% rename(UniqueID = variable) %>% 
  select(NAME,estimate,UniqueID)

# The UniqueID in nativity will be used when joining it to the table_var_clean table to get the country region names
nativity2 <- left_join(nativity,table_var_clean,by="UniqueID") %>% 
   select(NAME,estimate,UniqueID,Stub) %>% rename(Category=Stub, State=NAME)

# Get the line number from each UniqueID ** Note that this column already existed the table_var dataset
# str_split() splits a string at a certain character
split_ID <- str_split(nativity2$UniqueID, "_", simplify = TRUE) 
# Simplify: If FALSE, the default, returns a list of character vectors. If TRUE returns a character matrix
# Since simplify = TRUE, a matrix was returned so the code below returns the second column

# convert ID from char to numeric using as.numeric()
nativity2 <- nativity2 %>% mutate(ID = as.numeric(split_ID[,2])) 

# Create 2 columns that contain information on nativity of the population
nativity3 <- nativity2 %>% 
  mutate(status=if_else(ID<=12 & ID >=2,"Native","Foreign"),
         status_type=if_else(ID<=8 & ID >=5,"Born in the US",
          if_else(ID<=12 & ID >=10,"Born outside of the US",
            if_else(ID<=20 & ID >=15,"Naturalized US citizen",
                if_else(ID<=27 & ID >=22,"Not a US citizen","NA")))))

# delete rows where status_type=="NA" 
nativity_final <- nativity3[!(nativity3$status_type=="NA"),]

# Create summary tables

# 1- Total number of foreign born US citizens by state in descending order
naturalized <- nativity_final %>% filter(status_type=="Naturalized US citizen") %>% 
  group_by(State) %>% 
  summarise(total=sum(estimate)) %>% arrange(desc(total))

# CA has the largest number of foreign born US citizens. Where do they come from? 
naturalized_ca <- nativity_final %>% filter(status_type=="Naturalized US citizen", 
  State=="California") %>% 
  group_by(Category) %>% 
  summarise(total=sum(estimate)) %>% arrange(desc(total))

# The largest number of naturalized citizens in California come from Asia

# 2- Proportion of immigrants by state
perc_of_total <- nativity_final %>% group_by(State,status_type) %>% 
  summarise(total=sum(estimate)) %>% spread(status_type,total) %>% 
  mutate(total_pop=`Born in the US`+`Born outside of the US`+`Naturalized US citizen`+`Not a US citizen`,
         immigrant_pop=(`Naturalized US citizen`+`Not a US citizen`)/total_pop,
         foreignborn_pop=(`Naturalized US citizen`/total_pop)*100) %>% 
  arrange(desc(immigrant_pop))
 
# New York has the largest number of immigrants as a % of its total population

# NY Foreign born residents region of origin
NY_residents <- nativity_final %>% filter(status=="Foreign",State=="New York") %>% 
  select(State,Category,estimate) %>% group_by(Category) %>% summarise(total=sum(estimate)) %>% 
  arrange(desc(total))

# The largest number of immigrants in New York come from Latin America

# Where do Africans live in the US?
summary_african <- nativity_final %>% filter(Category=="Africa") %>% group_by(State) %>% 
  summarise(total=sum(estimate)) %>% 
  arrange(desc(total))

# bar chart showcasing the top 6 states with the largest number of immigrants from Africa
ggplot(head(summary_african))+ aes(x=State,y=total) + 
  geom_bar(stat="identity") +
  labs(title = "Top 6 states where immigrants from Africa live")

# Texas has the largest number of Africans in the US. Which African countries are represented in Texas?

# Create a vector that contains the list of African countries and use it with data pulled from the B05006 census table.
# The data was scraped from Wikipedia using ImportHTML function in Google Sheets
african_countries <- c('Nigeria' ,'Ethiopia' ,'Egypt' ,'Democratic Republic of the Congo' ,
                       'South Africa' ,'Tanzania' ,'Kenya' ,'Sudan' ,'Algeria' ,'Uganda' ,
                       'Morocco' ,'Mozambique' ,'Ghana' ,'Angola' ,'Ivory Coast' ,
                       'Madagascar' ,'Cameroon' ,'Niger' ,'Burkina Faso' ,'Mali' ,'Malawi' ,
                       'Zambia' ,'Somalia' ,'Senegal' ,'Chad' ,'Zimbabwe' ,'Rwanda' ,'Tunisia' ,
                       'Guinea' ,'Benin' ,'Burundi' ,'South Sudan' ,'Togo' ,'Eritrea' ,
                       'Sierra Leone' ,'Libya' ,'Republic of the Congo' ,'Central African Republic' ,
                       'Liberia' ,'Mauritania' ,'Namibia' ,'Botswana' ,'Lesotho' ,'Gambia' ,'Gabon' ,'Guinea-Bissau' ,
                       'Mauritius' ,'Equatorial Guinea' ,'Eswatini' ,'Djibouti' ,'Réunion (France)' ,'Comoros' ,
                       'Cabo Verde' ,'Western Sahara' ,'Mayotte' ,'São Tomé and Príncipe' ,
                       'Seychelles' ,'Saint Helena, Ascension and Tristan da Cunha','Other Eastern Africa','Other Middle Africa',
                       'Other Northern Africa','Other Southern Africa','Other Western Africa','Africa, n.e.c.')

# Get census data that breaks region of origin into countries. Filter for immigrants living in Texas.
tx_od <- get_acs(geography = "state", state="Texas",table = "B05006", survey = "acs5") %>%
  filter(estimate!=0) %>% rename(UniqueID = variable) %>% select(UniqueID:moe) 

# Left_join tx_od to table_var_clean to get the country names, delete rows that have 'NA'
tx_clean <- left_join(tx_od,table_var_clean,by="UniqueID") %>% na.omit() %>% 
  select(Stub,estimate) %>% rename(country=Stub)

# Filter for countries that are listed in the africa_countries vector
tx_africa <- tx_clean %>% filter(country %in% african_countries) %>% arrange(desc(estimate)) 

ggplot(head(tx_africa), aes(x=country,y = estimate)) + 
  geom_bar(stat = "identity") +
  labs(title = "Top 6 African countries (by pop) living in TX")

# Nigeria represents the largest group of Africans living in Texas

#########################################################################

# Analyzing DC's immigrant population using the B05006 census table
#   Which countries are represented in DC's immigrant population? And 
#   Where do immigrants live in DC?
#   Map by census tract to see if there is segregation

# Get data
dc_region <- get_acs(geography = "tract",state="DC", 
                     table = "B05002", survey = "acs5", geometry = TRUE) %>% 
  rename(UniqueID = variable)%>% filter(estimate!=0) 

# Clean data
dc_region2 <- left_join(dc_region,table_var_clean,by="UniqueID") %>% na.omit() 

dc_region_final <- dc_region2 %>% 
  mutate(status=if_else(Line<=12 & Line >=2,"Native","Foreign"),
         status_type=if_else(Line<=8 & Line >=5,"Born in the US",
                             if_else(Line<=12 & Line >=10,"Born outside of the US",
                                     if_else(Line<=20 & Line >=15,"Naturalized US citizen",
                                             if_else(Line<=27 & Line >=22,"Not a US citizen","NA")))))

dc_region_final <- dc_region_final[!(dc_region_final$status_type=="NA"),]

dc_region_final <- dc_region_final %>% filter(status=="Foreign") %>% 
  select(GEOID,NAME,Stub,estimate,geometry) %>% rename(region=Stub)

### create maps using different methods

# DC map (no data yet) using Tigris which contains spatials shape files
dc_roads <- roads("DC","District of Columbia") %>% filter(RTTYP %in% c("I","S","U"))
dc_water <- area_water("DC","District of Columbia")
dc_boundary <- counties("DC", cb = TRUE)
dc_tracts <- tracts("DC", cb = TRUE)

ggplot() + 
  geom_sf(data = dc_boundary, color = NA, fill = "white") +
  geom_sf(data = dc_tracts)+
  geom_sf(data = dc_water, color = "lightblue", fill = "lightblue")  +
  labs(title = "Washington DC Census Tract")

# Distribution of immigrants in DC
plot(dc_region_final["estimate"]) 

# Areas that are colored pink:yellow imply that a large number of the immigrant population live in that area.

# Distribution of immigrants in DC by region of origin
ggplot(dc_region_final, aes(fill=estimate)) + geom_sf() +
  scale_fill_distiller(direction = 1) +
  facet_wrap(~region)

# The maps show that immigrants from Asia, Europe, and Latin America tend to live near each other
# Whereas immigrants from other Northern American countries and Oceania are more spread out
# Outside of the 2 census tracts that showcase population clusters, immigrants from Africa are also spread out

# Here's an interactive map of immigrant population in DC by census tract using mapview
mapview(dc_region_final, zcol = "estimate", legend = TRUE)
